### ISSUE TITLE
Request failed: Ogiltigt land: Sweden

### ISSUE THREAD

**Issue by joaqim** [FortnoxAB/csharp-api-sdk#242]
# Bug report
Every other country that I've tested in the EU works with the culture-independent English country name.

We can see on the Fortnox front-end that when you input Sweden as Country it auto corrects to 'Sverige'.
But in the API, Sweden is not accepted at all and throws a FortnoxApiException.

Same with Czechia, which is expected by Fortnox to be 'Czech Republic'.

## :computer: Code
```csharp
var isoCode = "SE"

// This should return English country name, but consider using InvariantCulture class instead.
var countryEnglishName = new RegionInfo(isoCode).EnglishName; 


var Invoice = new Invoice {
   ...
   Country = countryEnglishName,
   ...
}
...
await invoiceConnector.CreateAsync(invoice);
```
## Actual behavior
``` Request failed: Ogiltigt land: Sweden ```

## Expected behavior
We expect that all Country names conforming to English naming should be accepted by Fortnox as valid Country.

## Notes
I currently use this utility function to circumvent this issue:
```csharp
public static string GetEnglishName(string countryCode)
        {
            try
            {
                return countryCode.ToUpper() switch
                {
                    "SE" => "Sverige",
                    "CZ" => "Czech Republic",
                    _ => new RegionInfo(countryCode).EnglishName
                };
            }
            catch (Exception)
            {
                return $"Missing English Name for {countryCode}";
            }
        }
```

**Comment by joaqim** [comment]
This seems to have been resolved without breaking changes, i.e both Sverige and Sweden now seems to be accepted as valid Country.

**Comment by richardrandak** [comment]
Have you change some settings or anything?
I can still reproduce the issue with my sandbox..

**Comment by joaqim** [comment]
It might be as simple as my missing the Api Exception, I'm dealing with issues related to that as I'm moving away from exceptions to non-fatal warnings instead to allow the application to continue running.

I'm now wondering if it is specifically Customer connector Update/Create that complains about Country, instead of the Invoice which is what I assumed at first.

**Comment by richardrandak** [comment]
Well, I am not responsible for the Fortnox API and I am not sure if the SDK should "cover" this issue by doing translation... I will just report the issue to Fortnox support and see what's behind this

**Comment by richardrandak** [comment]
So, I spoke with the support, and the Fortnox developers are aware of this issue already, so it will be fixed... eventually :)

**Comment by xpagedeveloper** [comment]
I think that the problem is like this. If the invoice has swedish (SE) as language the Swedish name for the country is needed.
If the Invoice has any other countrycode probably english then the english name apply.
Check out this issue and that repo for Ruby have a fix for it and all official values.
https://github.com/accodeing/fortnox-api/issues/153
